CFLAGS = -Wall -Wextra -Werror -std=gnu11 -fopenmp -O3

.PHONY: all
all: task1_master task1_close task1_spread

.PHONY: clean
clean:
	$(RM) task1_master task1_close task1_spread

task1_master: task1_master.c

task1_close: task1_close.c

task1_spread: task1_spread.c

